function impute_bertrand(path,spec)


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% This function imputes Bertrand prices and implied marginal costs under an
% assumption that the data are generated by Bertrand competition.
% Practically this entails passing the discount factor df==0 through
% existing code. ICCs do not matter for the analysis.
%
% Called by:
%   - main_v7.m
% Calls the following user-specified functions:
%   - main_data.m
%   - f_impute_mc.m
% Saved results are loaded in:
%   - results_analysis.m
%   - results_costregs.m
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Data required for imputation
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Loading demand results
cd(strcat(path.data2))
load daugfile daugfile
cd(strcat(path.code1))
    
% Main data 
[vars,ids] = main_data(path,spec);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Prepping
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

%Pick the relevant cities
temp = ismember(ids.fiscid,[2006,2007,2010,2011]).*ismember(ids.cityid,spec.city_in);
mktvec = unique(ids.cdid(temp==1))';
mktnums = 1:length(mktvec);

% Shell files
numProd = length(unique(ids.prodid));
mcmat = -999*ones(numProd,length(mktvec));

% Loop through each of the specified CDID (city*period) within mktvec
for m=mktnums

    % Picking the CDID
    mktid = mktvec(m);
     
    % Impute marginal costs and profit
    [mc0,~,~] = f_impute_mc(0,mktid,vars,ids,daugfile,spec);
       
    % Storing marginal cost in shell file
    mcx = [mc0; -998*ones(numProd-length(mc0),1)];
    mcmat(:,m) = mcx;
           
end

% Marginal cost vector
mc = mcmat(:);
mc = mc(mc~= -998);


%%%%%%%%%%%%%%%%%%
% Storing results
%%%%%%%%%%%%%%%%%%

cd(strcat(path.data2))

save sres_bertrand mc 

cd(strcat(path.code1))

