#! python


def build(ctx):
	
	for s in ['syllabus_micro_mae',
	'0_introduccion','1_estatico_completa','ayudantia1_estatico_completa',
	'sobre_ti',
	'2_dinamico_completa', 'ayudantia2_dinamica_completa',
	'3_estatico_incompleta', 'tarea_1']:
		ctx(features='tex',
		source=s + '.tex',
		prompt=1,name=s)
		# Install to the project root.
		ctx.install_files(
			ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
			s + '.pdf')
	
	
	
	
	"""
	# notes 0
	ctx(
	features='tex',
	type='xelatex',
	source='0_intro.tex',
	prompt=0,
	name='0_intro'
	)
	
	ctx.install_files(
	ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
	'0_intro.pdf'     )
	
	# notes 1a
	############
	ctx(
	features='tex',
	type='xelatex',
	source='1a_conduct_homogeneous.tex',
	prompt=0,
	name='1a_conduct'
	)
	
	ctx.install_files(
	ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
	'1a_conduct_homogeneous.pdf'
	)
	
	# notes 1b
	###########
	ctx(
	features='tex',
	type='xelatex',
	source='1b_conduct_heterogeneous.tex',
	prompt=0,
	name='1b_conduct'
	)
	
	ctx.install_files(
	ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
	'1b_conduct_heterogeneous.pdf'
	)

	# research agenda
	#################
	ctx(
	features='tex',
	type='xelatex',
	source='research_agenda.tex',
	prompt=0,
	name='research_agenda'
	)
	
	ctx.install_files(
	ctx.env.PROJECT_PATHS['PROJECT_ROOT'].abspath(),
	'research_agenda.pdf'
	)

	"""
